import tailwindcssAnimate from "tailwindcss-animate";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
    "./src/components/ui/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    fontFamily: {
      sans: ["Poppins", "sans-serif"],
    },
    borderRadius: {
      "3xl": "1.5rem",
      button: "100px",
    },
    colors: {
      primary: "#FFB4A5",
      surfaceTint: "#FFB4A5",
      onPrimary: "#650A00",
      primaryContainer: "#E32400",
      onPrimaryContainer: "#FFFFFF",
      secondary: "#FFB4A5",
      onSecondary: "#650A00",
      secondaryContainer: "#811101",
      onSecondaryContainer: "#FFC8BD",
      tertiary: "#F8BD4B",
      onTertiary: "#422D00",
      tertiaryContainer: "#996C00",
      onTertiaryContainer: "#FFFFFF",
      error: "#FFB4AB",
      onError: "#690005",
      errorContainer: "#93000A",
      onErrorContainer: "#FFDAD6",
      background: "#200F0B",
      onBackground: "#FEDBD4",
      surface: "#200F0B",
      onSurface: "#FEDBD4",
      surfaceVariant: "#5E3F39",
      onSurfaceVariant: "#E8BDB4",
      outline: "#AE8880",
      outlineVariant: "#5E3F39",
      shadow: "#000000",
      scrim: "#000000",
      inverseSurface: "#FEDBD4",
      inverseOnSurface: "#402B27",
      inversePrimary: "#BA1C00",
      primaryFixed: "#FFDAD3",
      onPrimaryFixed: "#3F0400",
      primaryFixedDim: "#FFB4A5",
      onPrimaryFixedVariant: "#8E1300",
      secondaryFixed: "#FFDAD3",
      onSecondaryFixed: "#3F0400",
      secondaryFixedDim: "#FFB4A5",
      onSecondaryFixedVariant: "#8B1A06",
      tertiaryFixed: "#FFDEA9",
      onTertiaryFixed: "#271900",
      tertiaryFixedDim: "#F8BD4B",
      onTertiaryFixedVariant: "#5E4100",
      surfaceDim: "#200F0B",
      surfaceBright: "#4A342F",
      surfaceContainerLowest: "#1A0A07",
      surfaceContainerLow: "#291713",
      surfaceContainer: "#2E1B17",
      surfaceContainerHigh: "#392521",
      surfaceContainerHighest: "#452F2B",
    },
    container: {
      center: true,
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};
